info: {}
name: rectangle_db821636
ports:
  e1:
    center:
    - -5.2
    - 0.0
    layer:
    - 203
    - 0
    name: e1
    orientation: 180.0
    port_type: electrical
    shear_angle: null
    width: 10.4
  e2:
    center:
    - 0.0
    - 5.2
    layer:
    - 203
    - 0
    name: e2
    orientation: 90.0
    port_type: electrical
    shear_angle: null
    width: 10.4
  e3:
    center:
    - 5.2
    - 0.0
    layer:
    - 203
    - 0
    name: e3
    orientation: 0.0
    port_type: electrical
    shear_angle: null
    width: 10.4
  e4:
    center:
    - 0.0
    - -5.2
    layer:
    - 203
    - 0
    name: e4
    orientation: 270.0
    port_type: electrical
    shear_angle: null
    width: 10.4
settings:
  centered: true
  layer: TE
  port_orientations:
  - 180
  - 90
  - 0
  - -90
  port_type: electrical
  size:
  - 10.4
  - 10.4
